# Generated by Django 5.2 on 2025-05-03 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(upload_to='study_materials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odf', 'odt', 'txt', 'jpg', 'jpeg', 'png', 'svg', 'ppt', 'pptx', 'xls', 'xlsx', 'csv', 'mp4', 'mov', 'webm', 'mp3', 'wav'])]),
        ),
    ]
