# Generated by Django 5.2 on 2025-04-20 18:59

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0002_alter_studymaterial_options_alter_studymaterial_file_and_more'),
        ('subjects', '0003_alter_chapter_estimated_duration_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='chapter',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='subject', chained_model_field='subject', null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.chapter'),
        ),
    ]
