# Generated by Django 5.2 on 2025-04-21 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0003_alter_studymaterial_chapter'),
        ('subjects', '0003_alter_chapter_estimated_duration_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.chapter'),
        ),
    ]
