# Generated by Django 5.2 on 2025-04-21 09:39

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0004_alter_studymaterial_chapter'),
        ('subjects', '0003_alter_chapter_estimated_duration_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-marks', '-created_at'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='subject', chained_model_field='subject', default=1, on_delete=django.db.models.deletion.CASCADE, to='subjects.chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='subjects.subject'),
            preserve_default=False,
        ),
    ]
