# Generated by Django 5.2 on 2025-05-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CIVIL', 'Civil Engineering'), ('COMP', 'Computer Engineering'), ('BSE', 'Software Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('CHEM', 'Chemical Engineering'), ('ELEC', 'Electrical Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('CIVR', 'Civil and Rural Engineering'), ('ARCH', 'Architecture Engineering'), ('AUTO', 'Automobile Engineering'), ('ELEN', 'Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('AERO', 'Aerospace Engineering'), ('AGRI', 'Agricultural Engineering')], max_length=10, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
