# Generated by Django 5.2 on 2025-04-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='related_disciplines',
        ),
    ]
