# Generated by Django 5.1.8 on 2025-04-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('MOCK', 'Mock Test'), ('SUBJECT', 'Subject Test'), ('CHAPTER', 'Chapter Quiz'), ('PAST', 'Past Paper'), ('PRACTICE', 'Practice Set')], default='MOCK', max_length=10),
        ),
    ]
