# Generated by Django 5.2 on 2025-04-21 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('MOCK', 'Mock Test'), ('SUBJECT', 'Subject Test'), ('CHAPTER', 'Chapter Quiz'), ('PAST', 'Past Paper')], db_index=True, default='MOCK', help_text='Select the category of the exam.', max_length=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
