# Generated by Django 5.2 on 2025-05-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
