# Generated by Django 5.1.8 on 2025-04-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_exam_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('MOCK', 'Mock Test'), ('SUBJECT', 'Subject Test'), ('CHAPTER', 'Chapter Quiz'), ('PAST', 'Past Paper'), ('PRACTICE', 'Practice Set')], db_index=True, default='MOCK', help_text='Select the category of the exam.', max_length=10),
        ),
    ]
