# Generated by Django 5.2 on 2025-05-06 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('disciplines', '0002_alter_discipline_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='disciplines.discipline'),
            preserve_default=False,
        ),
    ]
