# Generated by Django 5.1.8 on 2025-04-04 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_username'),
        ('disciplines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='disciplines',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='disciplines.discipline'),
        ),
    ]
