# Generated by Django 5.1.8 on 2025-04-08 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_studentprofile_disciplines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='discipline',
            field=models.CharField(blank=True, choices=[('CIVIL', 'Civil Engineering'), ('COMP', 'Computer Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('CHEM', 'Chemical Engineering'), ('ELEC', 'Electrical Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('CIVR', 'Civil and Rural Engineering'), ('ARCH', 'Architecture Engineering'), ('AUTO', 'Automobile Engineering'), ('ELEN', 'Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('AERO', 'Aerospace Engineering'), ('AGRI', 'Agricultural Engineering')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must start with '+977' or '00977' followed by a 10-digit number starting with 98 or 97.", regex='^(?:\\+977|00977)?(?:98|97)\\d{8}$'), django.core.validators.MinLengthValidator(9)]),
        ),
    ]
