# Generated by Django 5.2 on 2025-04-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('EXAM', 'Exam'), ('STUDY_MATERIAL', 'Study Material'), ('SYSTEM', 'System'), ('ANNOUNCEMENT', 'Announcement')], default='SYSTEM', max_length=20),
        ),
    ]
