# Generated by Django 5.2 on 2025-08-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studentprofile_first_name_studentprofile_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='discipline',
            new_name='program',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='university',
            field=models.CharField(default='', max_length=255),
        ),
    ]
