# Generated by Django 5.2 on 2026-01-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_discipline_studentprofile_program_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("STUDENT", "Student"), ("INSTRUCTOR", "Instructor")],
                default="STUDENT",
                help_text="User role: Student or Instructor",
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
