# Generated by Django 5.2 on 2025-04-20 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_groups_alter_user_user_permissions'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeditem',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='liked_items', to='core.studentprofile'),
            preserve_default=False,
        ),
    ]
