# Generated by Django 5.2 on 2025-04-21 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_remove_user_role'),
        ('likes', '0002_likeditem_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likeditem',
            unique_together={('student', 'content_type', 'object_id')},
        ),
        migrations.AddField(
            model_name='likeditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='likeditem',
            name='like',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
