# Generated by Django 5.1.8 on 2025-04-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study_materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(blank=True, related_name='tags', to='study_materials.question')),
                ('study_materials', models.ManyToManyField(blank=True, related_name='tags', to='study_materials.studymaterial')),
            ],
        ),
    ]
