# Generated by Django 5.2 on 2025-04-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='study_materials',
        ),
        migrations.AlterField(
            model_name='tag',
            name='label',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
