# Generated by Django 5.2 on 2025-05-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='-', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
