# Generated by Django 5.2 on 2025-05-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0002_remove_tag_questions_remove_tag_study_materials_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taggeditem',
            options={'verbose_name': 'Tagged Item', 'verbose_name_plural': 'Tagged Items'},
        ),
        migrations.AlterUniqueTogether(
            name='taggeditem',
            unique_together={('tag', 'content_type', 'object_id')},
        ),
    ]
