# Generated by Django 5.2 on 2025-04-20 18:20

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='estimated_duration',
        ),
        migrations.AddField(
            model_name='chapter',
            name='estimated_duration_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated time to complete in hours', null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='learning_objectives',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
