# Generated by Django 5.2 on 2025-04-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_remove_chapter_estimated_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='estimated_duration_hours',
            field=models.PositiveIntegerField(default='3', help_text='Estimated time to complete in hours'),
            preserve_default=False,
        ),
    ]
