# Generated by Django 5.2 on 2025-04-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['-created_at'], 'verbose_name': 'badge', 'verbose_name_plural': 'badges'},
        ),
        migrations.AddField(
            model_name='badge',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
