# Generated by Django 5.2 on 2025-05-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_badge_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(default=1, upload_to='badges/icons/'),
            preserve_default=False,
        ),
    ]
