# Generated by Django 5.2 on 2025-04-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_alter_badge_options_badge_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-awarded_at']},
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
