# Generated by Django 5.2 on 2025-04-22 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_alter_userbadge_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ['-created_at'], 'verbose_name': 'point', 'verbose_name_plural': 'points'},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-awarded_at'], 'verbose_name': 'user badge', 'verbose_name_plural': 'user badges'},
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('EXAM', 'Exam'), ('BADGE', 'Badge'), ('BONUS', 'Bonus'), ('SYSTEM', 'System Generated')], default='SYSTEM', max_length=20),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
    ]
