name: Add contributors
on:
  push:
    branches:
      - main
jobs:
  add-contributors:
    runs-on: ubuntu-latest
    name: Generate Contributors List
    steps:
      - uses: actions/checkout@v2
      - uses: akhilmhdh/contributors-readme-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
