name: Add contributors
on:
  push:
    branches:
      - main
jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: contributors-readme-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: README.md