name: Build and Publish Docker Image
on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - ".github/workflows/docker-build-publish.yml"
      - "docker-compose.yml"
      - "requirements.txt"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t mdjiyaulhaq/er-sathi:latest .

      - name: Push Docker Image
        run: docker push mdjiyaulhaq/er-sathi:latest
